server:
  port: 4004 #our API Gateway listens on port 4004

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            ## http://localhost:4004/auth/login (path that client sends)
            ## spring api gateway will check the path against our predicates then applies the filter
            ## API GATEWAY -> http://auth-service:4005/login
            - id: auth-service-route
              uri: http://auth-service:4005 #where auth is running on our docker container
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1 #removes everything after the first / and attaches the rest to uri
            ## REST CLIENT -> http://localhost:4004/api/patients
            ## API GATEWAY -> http://patient-service:4000/patients
            ## PATIENT SERVICE (SPRING BOOT APP) -> /patients -> Patients Array
            ## Route for /api/patients/** to patient service
            - id: patient-service-route
              uri: http://patient-service:4000
              predicates:
                - Path=/api/patients/**
              filters:
                - StripPrefix=1
                - JwtValidation #Now validation filter will only affect routes to patient service
                ##convention based naming

              ## REST-CLIENT -> http://localhost:4004/api-docs/patients
              ## API-GATEWAY -> http://patient-srevice:4000/v3/api-docs
            - id: api-docs-patient-route
              uri: http://patient-service:4000
              predicates:
                - Path=/api-docs/patients # sending patient docs to patient service
              filters:
                - RewritePath=/api-docs/patients,/v3/api-docs
            ## API Gateway routes hides the implementation of the actual route using routing rules
            - id: api-docs-auth-route
              uri: http://auth-service:4005
              predicates:
                - Path=/api-docs/auth # sending auth docs to auth service
              filters:
                - RewritePath=/api-docs/auth,/v3/api-docs

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

logging:
  level:
    org.springframework.cloud.gateway: TRACE




